### PR TITLE
NDA workshop documentation

### PR DESCRIPTION
**Pull request by nicolasdb**
During FAB14 Toulouse. 
We were asked (Rasmus and I) to host a workshop about documentation for Vulca. 

image

Here, I want to work the path of what we did and conclude. by working together on a documentation of what happend then. 
I want it to be contributive, I want to better use github and I want it to do it better together. 

So if I just ask like that to @nightvisi0n (Julian) from FAU-Fablab (Germany) 
Will it work? :)

Then I need to find out the "blaz" github of Rasmus....

### CODE REVIEW

**Comment by nicolasdb** [comment]
- [ ] First, I asked about pictures from that day. I'm waiting postprocessing from Vulca team. 
- [ ] then I draw.io some illustration about the process we use. Files are in `\assets\docs`
- [ ] I'll need now to share this in the team. So they could help me with names and questions. 

nda workshop diagram

- [ ] I'll start to write something.

**Comment by nicolasdb** [comment]
Based one of mine; 

Questions was : 
- What is the ideal documentation for fablab managment?

image

**Comment by nicolasdb** [comment]
nda conclusion

**Comment by nicolasdb** [comment]
### notes about who document where?
- Charlene (la fabrique du Loch) : Wikifab
- Nicolasdb : github + github pages

**Comment by nicolasdb** [comment]
image

**Comment by nicolasdb** [comment]
nda conclusion

**Comment by nicolasdb** [comment]
image

**Comment by nicolasdb** [comment]
maxresdefault

**Comment by nicolasdb** [comment]
maxresdefault

**Comment by nicolasdb** [comment]
nda workshop rythm

nda workshop flow

**Comment by zuperninja** [comment]
I'm glad if we can chosse our platform. Love the idea of rss. Maybe a search engine only with makers website ? Bootstrap who will search intonmetadata for every articles and a ''submit your website''. News feed + theme + tools used

**Comment by nicolasdb** [comment]
Cool, because we discuss very quickly about that with Massimo Menichinelli from fablab BCN, he's working on the new fablabs.io which could host the search engine focus on the network of fablabs 
As soon as we have  a first draft of the idea, I'll reconnect with him.

**Pull request merged**
